const port = 8080

const path = require('path');
let express = require('express');
let app = express();

const {
    getCustomerByEmail,
    insertCustomer,
    getAllBooks,
    getBooksWithAuthors,
    getAuthorByName,
    getBooksByAuthor,
    getCartByCustomer,
    getCustomerById,
    updateCustomer,
    removeFromCart,
    addToCart,
    getAllCustomers,
    editCustomer,
    getBookById,
    editBook,
    getAuthorById,
    getAllAuthors,
    editAuthor,
    removeBook,
    createBook,
    createAuthor,
    removeAuthor,
    removeCustomer,
    createCustomer
} = require('./public/script');

const e = require("express");
const session = require('express-session');

app.use(express.static(path.join(__dirname, 'public')));
app.use(express.json());
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.use(express.urlencoded({extended: true}))

// auth generated by chat
app.use(session({
    secret: 'secret-key',
    resave: false,
    saveUninitialized: false,
    cookie: {
        httpOnly: true
    }
}));
//============login endpoint============
app.get('/', (req, res) =>{

    console.log("Logging in...")
    res.render('form', {
        error:null
    })
});

//===============logout=================
app.get('/logout', requireLogin, (req, res) => {
    req.session.destroy(() => {
        res.redirect('/');
    });
});

//========registration endpoint========
app.get('/registration', (req, res) =>{

    res.render('registration', {
        error:null
    })
});

//=====================books list=======================
app.get('/books', requireLogin, async (req, res) => {
    let rows = await getBooksWithAuthors();
    let customer = await getCustomerById(req.session.userId);

    if(customer && customer.admin === 1){
        res.render('adminBookList', {
            error: null,
            rows: rows
        });
    }else{
        res.render('books', {
            error: null,
            rows: rows
        })
    }

    //console.log("on backend: ")
    //console.log(rows)
});

//======================customer's cart==================
app.get('/cart', requireLogin, async (req, res) =>{
    let rows = await getCartByCustomer(req.session.userId);
    let total = 0;
    for(let row of rows){
        //console.log(rows);
        //console.log(row);
        //console.log(row.price);
        total+=row.price;
    }

    res.render('cart', {
        error: null,
        rows: rows,
        total: total
    });
});

//==================books by author=====================
app.get('/filtered/:authorName', requireLogin, async (req, res) =>{
    let rows = await getBooksByAuthor(req.params.authorName);

    res.render('filteredTable', {
        author: req.params.authorName,
        rows: rows
    });
});

//================remove book from cart=================
app.post('/cart/:cartId', requireLogin, async (req, res)=>{
    await removeFromCart(req.params.cartId, req.session.userId);
    res.redirect('/cart');
});

//=================add book to cart====================
app.post('/book/:bookId', requireLogin, (req, res)=>{
    addToCart(req.params.bookId, req.session.userId);
});

//===================profile============================
app.get('/profile', requireLogin, async (req, res)=>{
    let row = await getCustomerById(req.session.userId);

    console.log(row);
    console.log(req.session.userId);
    console.log(row.Name + "\n"
                + row.LastName + "\n"
                + row.email + "\n")

    res.render('profile', {
        error: null,
        row: row
    });
});



//===============registration data validation============
app.post('/validate', async (req, res) => {
    let {name, lastName, email, password} = req.body;
    console.log("inside backend: " +  name + " " + lastName + " " + email + " " + password);

    let message = "";

    if (name === null || lastName === null || email === null || password === null) {
        console.log("all fields must be not empty")
        message += "all fields must be not empty\n"
    }

    //ai generated regex
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
        console.log("not an email")
        message += "not an email\n"
    }
    if (!/[A-Z]/.test(password)) {
        console.log("password doesn't have a capital letter")
        message += "password doesn't have a capital letter\n"
    }
    //ai generated regex
    if (!/\d/.test(password)) {
        console.log("password doesn't have at least one digit")
        message += "password doesn't have at least one digit\n"
    }
    //ai generated regex
    if (!/[!@#$%^&*(),.?":{}|<>_]/.test(password)) {
        console.log("password has no special character")
        message += "password has no special character\n"
    }

    let customer = await getCustomerByEmail(email);
    //console.log(customer.json())

    if (message) {
        res.json({message})
    } else {
        if (customer) {
            res.json("this email is taken");
        } else {
            insertCustomer(name, lastName, email, password);
            res.json({success: true});
        }
    }
});

//==============edit profile endpoint=================
app.get('/editProfile', requireLogin, async (req, res)=>{
    let row = await getCustomerById(req.session.userId);

    res.render('editForm', {
        row: row,
        error: null
    });
})

//==============edit profile validation==================
app.post('/validateEdit', requireLogin, async (req, res) => {
    let {name, lastName, email, password} = req.body;
    console.log(name + " " + lastName + " " + email + " " + password);

    let message = "";

    if (name === null || lastName === null || email === null || password === null) {
        console.log("all fields must be not empty")
        message += "all fields must be not empty\n"
    }

    //ai generated regex
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
        console.log("not an email")
        message += "not an email\n"
    }
    if (!/[A-Z]/.test(password)) {
        console.log("password doesn't have a capital letter")
        message += "password doesn't have a capital letter\n"
    }
    //ai generated regex
    if (!/\d/.test(password)) {
        console.log("password doesn't have at least one digit")
        message += "password doesn't have at least one digit\n"
    }
    //ai generated regex
    if (!/[!@#$%^&*(),.?":{}|<>_]/.test(password)) {
        console.log("password has no special character")
        message += "password has no special character\n"
    }

    let customer = await getCustomerByEmail(email);
    //console.log(customer.json())

    if (message) {
        res.json({message})
    } else {
        if (customer && customer.customerId !== req.session.userId) {
            res.json("this email is taken");
        } else {
            //let customerId = await getCustomerByEmail(email);
            updateCustomer(name, lastName, email, password, req.session.userId);
            res.json({success: true});
        }
    }
});

//=======================login============================
app.post('/login', async (req, res) =>{

    const customer = await getCustomerByEmail(req.body.email);

    if (!customer) {
        return res.render('form', {
            error: "User with this email doesn't exist"
        });
    }

    if(customer.password !== req.body.password){
        console.log(false);
        return res.render('form', {
            error: "Incorrect password"
        })
    }

    req.session.userId = customer.customerId;
    req.session.email = customer.email;
    req.session.role = customer.admin;

    res.redirect('/books');
/*
    return res.render('form', {
        error: "OK"
    })
 */

    //res.writeHead(200, {'Content-Type': 'text/html'});
    //res.end(req.body.email + " " + req.body.password);
});

//=======================edit endpoint============================
app.get('/editForm', async (req, res) =>{


});

//=====================admin functionality=======================
//=======================all customers===========================
app.get('/customersList', requireAdmin, async (req, res)=>{
    let rows = await getAllCustomers();

    res.render('adminCustomersList', {
        error: null,
        rows: rows
    });
});

app.get('/editCustomerForm/:customerId', requireAdmin, async (req, res)=>{
    let row = await getCustomerById(req.params.customerId);

    console.log(row);
    console.log(req.params.customerId);

    res.render('editCustomerForm', {
        row: row,
        error: null
    });
});

app.post('/editCustomer', requireAdmin, async (req, res) =>{
    let {id, name, lastName, email, password, previousId} = req.body;
    console.log(id + " "+ name + " " + lastName + " " + email + " " + password);

    let message = "";

    if (id === "" ||name === "" || lastName === "" || email === "" || password === "") {
        console.log("all fields must be not empty")
        message += "all fields must be not empty\n"
    }

    if(id<0){
        console.log("id cannot be less than 0");
        message+= "id cannot be less than 0";
    }

    //ai generated regex
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
        console.log("not an email")
        message += "not an email\n"
    }
    if (!/[A-Z]/.test(password)) {
        console.log("password doesn't have a capital letter")
        message += "password doesn't have a capital letter\n"
    }
    //ai generated regex
    if (!/\d/.test(password)) {
        console.log("password doesn't have at least one digit")
        message += "password doesn't have at least one digit\n"
    }
    //ai generated regex
    if (!/[!@#$%^&*(),.?":{}|<>_]/.test(password)) {
        console.log("password has no special character")
        message += "password has no special character\n"
    }

    let customer = await getCustomerByEmail(email);
    //console.log("customer.customerId "+customer.customerId + " : " + previousId)
    let customerById = await getCustomerById(id);

    if (message) {
        res.json({message})
    } else {
        if(customerById && customerById.customerId !== Number(previousId)){
            res.json("this id is taken");
        }else
        if (customer && customer.customerId !== Number(previousId)) {
            res.json("this email is taken");
        } else {
            //let customerId = await getCustomerByEmail(email);
            editCustomer(id, name, lastName, email, password, previousId);
            res.json({success: true});
        }
    }
});

//======================remove customer=========================
app.post('/removeCustomer/:customerId', requireAdmin, async (req, res)=>{
    await removeCustomer(req.params.customerId);

    res.redirect('/customersList');
});

//==================create Customer Form========================
app.get('/createCustomerForm', requireAdmin, async (req, res)=>{
    res.render('createCustomerForm', {
        error: null
    })
});

//=================validate and create Customer=================
app.post('/createCustomer', requireAdmin, async (req, res)=>{
    let {Name, LastName, Email, Password, Admin} = req.body;

    let message = "";

    if (Name === "" || LastName === "" || Email === "" || Password === "") {
        console.log("all fields must be not empty")
        message += "all fields must be not empty\n"
    }

    //ai generated regex
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(Email)) {
        console.log("not an email")
        message += "not an email\n"
    }
    if (!/[A-Z]/.test(Password)) {
        console.log("password doesn't have a capital letter")
        message += "password doesn't have a capital letter\n"
    }
    //ai generated regex
    if (!/\d/.test(Password)) {
        console.log("password doesn't have at least one digit")
        message += "password doesn't have at least one digit\n"
    }
    //ai generated regex
    if (!/[!@#$%^&*(),.?":{}|<>]/.test(Password)) {
        console.log("password has no special character")
        message += "password has no special character\n"
    }

    let customer = await getCustomerByEmail(Email);
    //console.log(customer.json())

    if (message) {
        res.json({message})
    } else {
        if (customer) {
            res.json("this email is taken");
        } else {
            await createCustomer(Name, LastName, Email, Password, Admin);
            res.json({success: true});
        }
    }
});

//======================admin book list=========================
app.get('/editBookForm/:bookId', requireAdmin, async (req, res)=>{
    let row = await getBookById(req.params.bookId);

    res.render('editBookForm', {
        error: null,
        row: row
    })
});

//======================== edit book ============================
app.post('/editBook', requireAdmin, async (req, res)=>{
    let {bookId, Title, Genre, Author, Price, Img, previousId} = req.body;

    let message = "";

    if(bookId === "" || Title === "" || Genre === "" || Author === "" || Price === "" || Img === ""){
        console.log("Every field must be not empty");
        message+="Every field must be not empty\n";
    }

    if(bookId < 0){
        console.log("Id cannot be less than 0");
        message+="Id cannot be less than 0\n";
    }

    if(Author < 0){
        console.log("Author Id cannot be less than 0");
        message+="Author Id cannot be less than 0\n";
    }

    if(Price < 0){
        console.log("Price cannot be less than 0");
        message+="Price cannot be less than 0\n";
    }

    if(message){
        res.json({message});
    }
    else{

        let book = await getBookById(bookId);
        let author = await getAuthorById(Author);
        if(author){
            console.log(author);
        }

        if(book && book.bookId !== Number(previousId)){
            res.json("This id is taken");
        }else
            if(!author){
                res.json("Author with this id doesn't exist");
            }
            else{
                editBook(bookId, Title, Genre, Author, Price, Img, previousId);
                res.json({success: true});
        }
    }
});

//=====================remove book==========================
app.post('/removeBook/:bookId', requireAdmin, async (req, res)=>{
    await removeBook(req.params.bookId);
    res.redirect('/books');
});

//===================create book form=======================
app.get('/createBookForm', requireAdmin, async (req, res)=>{
    res.render('createBookForm', {
        error: null
    });
});

//=================validate and create book==================
app.post('/createBook', requireAdmin, async (req, res)=>{
    let {Title, Genre, Author, Price, Img} = req.body;

    let message = "";

    if(Title === "" || Genre === "" || Author === "" || Price === "" || Img === ""){
        console.log("Every field must be not empty");
        message+="Every field must be not empty\n";
    }

    if(Author < 0){
        console.log("Author Id cannot be less than 0");
        message+="Author Id cannot be less than 0\n";
    }

    if(Price < 0){
        console.log("Price cannot be less than 0");
        message+="Price cannot be less than 0\n";
    }

    if(message){
        res.json({message})
    }
    else{
        let author = await getAuthorById(Author);

        if(!author){
            res.json("Author with this id doesn't exist");
        }
        else{
            await createBook(Title, Genre, Author, Price, Img);
            res.json({success: true});
        }
    }
});

//======================author list==========================
app.get('/authorList', requireAdmin, async (req, res)=>{
    let rows = await getAllAuthors();

    res.render('authorList', {
        error: null,
        rows: rows
    })
});

//=====================edit author form=======================
app.get('/editAuthorForm/:authorId', requireAdmin, async (req, res)=>{
    let row = await getAuthorById(req.params.authorId);

    res.render('editAuthorForm', {
        error: null,
        row: row
    })
});

//================validate and edit author====================
app.post('/editAuthor', requireAdmin, async (req, res)=>{
    let {authorId, authorName, LastName, previousId} = req.body;

    let message = '';

    if(authorId === "" || authorName === "" || LastName === ""){
        console.log("Every field must be not empty");
        message+="Every field must be not empty\n";
    }

    if(authorId < 0){
        console.log("Id cannot be less than 0");
        message+="Id cannot be less than 0\n";
    }

    let author = await getAuthorById(authorId);

    if(message){
        res.json({message});
    }
    else
        if(author && author.authorId !== Number(previousId)){
            res.json("This id is taken");
        }
        else{
            editAuthor(authorId, authorName, LastName, previousId);
            res.json({success: true});
        }
});

//===================create author form======================
app.get('/createAuthorForm', requireAdmin, async (req, res)=>{
    res.render('createAuthorForm', {
        error: null
    });
});

//================ validate and create author ================
app.post('/createAuthor', requireAdmin, async (req, res)=>{
    let {authorName, LastName} = req.body;

    let message = "";

    if(authorName === "" || LastName === ""){
        console.log("Every field must be not empty");
        message+="Every field must be not empty\n";
    }

    if(message){
        res.json({message});
    }else{
        await createAuthor(authorName, LastName);
        res.json({success: true});
    }
});

//=======================remove Author=======================
app.post('/removeAuthor/:authorId', requireAdmin, async (req, res)=>{
    await removeAuthor(req.params.authorId);

    res.redirect('/authorList');
});


//generated
//=======================middleware==========================
function requireLogin(req, res, next) {
    if (!req.session.userId) {
        return res.redirect('/');
    }
    next();
}

function requireAdmin(req, res, next) {
    if (!req.session.userId || req.session.role !== 1) {
        return res.redirect('/books');
    }
    next();
}
//=========================================================================

app.listen(port, () => {
    console.log(`App listening on port ${port}`)
});
